on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      - uses: actions/checkout@master  # 第一步，下载代码仓库

      - name: Set node version 16 # 第二步安装 node 环境
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Deps # 安装项目依赖
        run: npm install

      - name: lint # 项目构建
        run: pnpm run lint
